### 게임아이디 불러오기
POST http://localhost:18080/
Content-Type: application/json

{
  "email": "{{email}}",
  "password" : "{{password}}"
}

###

POST http://localhost:18080/
Content-Type: application/json

{
  "email": "{{email}}",
  "password" : "{{password}}",
  "nickname": "{{nickname}}"
}

###

POST http://localhost:18080/
Content-Type: application/json

{
  "email": "{{email}}",
  "password" : "{{password}}",
  "nickname": "{{nickname}}",
  "mode": "MY_BEST"
}


###

POST https://piudb-crawling-x5kgeugtqa-an.a.run.app
Content-Type: application/json

{
  "email": "{{email}}",
  "password" : "{{password}}"
}

###

POST https://piudb-crawling-x5kgeugtqa-du.a.run.app
Content-Type: application/json

{
  "email": "{{email}}",
  "password" : "{{password}}",
  "nickname": "{{nickname}}",
  "mode": "MY_BEST"
}