POST http://localhost:18080/
Content-Type: application/json

{
  "email": "{{email}}",
  "password" : "{{password}}",
  "nickname": "{{nickname}}"
}

###

POST https://piudb-crawling-x5kgeugtqa-an.a.run.app
Content-Type: application/json

{
  "email": "{{email}}",
  "password" : "{{password}}",
  "nickname": "{{nickname}}"
}